### ISSUE TITLE
perl is a good language however

### ISSUE THREAD

**Issue by TotallyNotAHaxxer** [evilmog/ntlmv1-multi#11]
```pl

  
#!/usr/bin/perl

sub prhex {
    my $x,$v = shift;
    print pack("H*",$v);
}

if ($ARGV[0] eq "-h") {
   prhex ($ARGV[1]);
   exit(0);
}

while (<>) {
   chop;
   prhex($_);
   print("\n");
}

```

why not do that in python? i use other languages in my projects to but it has to be a big project for me to do so, especially if the code is short ill just convert it to a new language, since this project is a bit lighter i suggest making this perl script into python, just cause it does not have a place other than printing hex which you can do easily in python

**Comment by evilmog** [comment]
Because its a legacy script from the development of the app and is being removed. Also this entire repo is being merged into hashcat-utils which uses a mix of languages.
