### ISSUE TITLE
The readme file 

### ISSUE THREAD

**Issue by spextat0r** [evilmog/ntlmv1-multi#14]
Really enjoyed the talk you gave and when I went to try this out I wanted to validate that everything was working nicely but following the readme hashcat fails to crack with the given DES keys. After playing with it the ntlm-to-des converter you have sheds light.

Here is the output if you just follow the readme and echo the ntlm-and-des-converter.py output 
![image](https://github.com/user-attachments/assets/06e93009-dd30-414f-a1ef-f38020d01e94)
![image](https://github.com/user-attachments/assets/691d5694-5f58-4b35-9c02-f2ce4e080632)

If you use ntlm-to-des.py it also includes that you need to wrap the des keys in $HEX[des-key-here]
![image](https://github.com/user-attachments/assets/9dae1489-ed7b-490b-8956-a9d7cff969f2)
This works and hashcat returns a cracked status for each key
![image](https://github.com/user-attachments/assets/01de0429-f44b-4086-a3b5-9a23682fc0e8)

Still a really awesome attack path just needs the "Testing with the des converter" readme section to be updated so im the only one who needs to spend time cursing at hashcat

**Comment by evilmog** [comment]
Ntlm-and-des-converter wasn't written by me, I'll remove the tool from the
repo, ntlm-to-des.py is the correct implementation, I'll update the readme

**Comment by evilmog** [comment]
> Really enjoyed the talk you gave and when I went to try this out I wanted to validate that everything was working nicely but following the readme hashcat fails to crack with the given DES keys. After playing with it the ntlm-to-des converter you have sheds light.
> 
> Here is the output if you just follow the readme and echo the ntlm-and-des-converter.py output ![image](https://private-user-images.githubusercontent.com/57763139/371811137-06e93009-dd30-414f-a1ef-f38020d01e94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTE5OTMsIm5iZiI6MTcyNzk5MTY5MywicGF0aCI6Ii81Nzc2MzEzOS8zNzE4MTExMzctMDZlOTMwMDktZGQzMC00MTRmLWExZWYtZjM4MDIwZDAxZTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDIxNDEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZjkwZTYzMjdhMWE2OTk2N2MyOTIyMjA1NWI0MGI2YTFmZDI4ZGQ2NzkwODgyYWZhOWMyMzlhNGM3ZmY3MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QgyJ4hdqsjRWNgi1ExiyBqSHVxOznVA13bUHCt7Da3A) ![image](https://private-user-images.githubusercontent.com/57763139/371810961-691d5694-5f58-4b35-9c02-f2ce4e080632.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTE5OTMsIm5iZiI6MTcyNzk5MTY5MywicGF0aCI6Ii81Nzc2MzEzOS8zNzE4MTA5NjEtNjkxZDU2OTQtNWY1OC00YjM1LTljMDItZjJjZTRlMDgwNjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDIxNDEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZTk3ZmQ3ZTY4MWFkZDkxM2FlZjc3NzFhY2Y4NDgxMGFhZTBmMjE2MmJmYmJjMDBkODFlOWFiYTcyNDc3OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3gArT-e1hdtljMPk60TJPDL468PY6Gf_2vsEJsMyyzs)
> 
> If you use ntlm-to-des.py it also includes that you need to wrap the des keys in $HEX[des-key-here] ![image](https://private-user-images.githubusercontent.com/57763139/371811117-9dae1489-ed7b-490b-8956-a9d7cff969f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTE5OTMsIm5iZiI6MTcyNzk5MTY5MywicGF0aCI6Ii81Nzc2MzEzOS8zNzE4MTExMTctOWRhZTE0ODktZWQ3Yi00OTBiLTg5NTYtYTlkN2NmZjk2OWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDIxNDEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljYjlkZTY0YmM3YzczOTQwNjllMGNhYjlhZjNkOWFkM2NhMDE0ZDdlYzBiMGQ2Y2M3YWMzOTk1YzE1OGU0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XSg3Gj1m-AGiOc9JgbKBE-hgH7Z6bP-PJoxR1JdPwK0) This works and hashcat returns a cracked status for each key ![image](https://private-user-images.githubusercontent.com/57763139/371811024-01de0429-f44b-4086-a3b5-9a23682fc0e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTE5OTMsIm5iZiI6MTcyNzk5MTY5MywicGF0aCI6Ii81Nzc2MzEzOS8zNzE4MTEwMjQtMDFkZTA0MjktZjQ0Yi00MDg2LWEzYjUtOWEyMzY4MmZjMGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDIxNDEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjOWIyMGQ1YjcwMDdiZDRjMzI5MmI0YzRmOWJjY2RlOGYyMTMzOGM3YjNlNGJmYTMzY2U5ODBkMzJjNjVkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aGB2eQc_XJsjut8N6Gt3Z6dh8N439lfXjA8F5xzmRoY)
> 
> Still a really awesome attack path just needs the "Testing with the des converter" readme section to be updated so im the only one who needs to spend time cursing at hashcat

I corrected the readme, please review

**Comment by spextat0r** [comment]
Looks like it shows up in three places you got the one in the "NTLM hash to DES Key Converter for data validation testing" section but the one in the "NTLMv1 without ESS" section is still there and the one in the "NTLMv1 with ESS" section.

**Comment by evilmog** [comment]
Sorry about that, I'll take care of that tonight, I'll ping when done

**Comment by evilmog** [comment]
ok double check that now

**Comment by spextat0r** [comment]
That works
