### ISSUE TITLE
Readme states MS-CHAPv1

### ISSUE THREAD

**Issue by Meatballs1** [evilmog/ntlmv1-multi#4]
Could you clarify if it only targets MS-CHAPv1, original thread suggests v2? 

https://hashcat.net/forum/thread-5912.html

**Comment by evilmog** [comment]
README says MSCHAPv2 which is equivalent to NTLMv1, this is not for MSCHAPv1

**Comment by Meatballs1** [comment]
```
This tool modifies NTLMv1/NTLMv1-ESS/MSCHAPv1 hashes so they can be cracked with DES Mode 14000 in hashcat
```

? :)
