### ISSUE TITLE
Time expectations for hashcat?

### ISSUE THREAD

**Issue by 7MinSec** [evilmog/ntlmv1-multi#7]
Hello!

I'm going through your steps to handle a NTLMv1 *with* SSP and am at this step:

```
./hashcat -m 14000 -a 3 -1 charsets/DES_full.charset --hex-charset hashes.txt ?1?1?1?1?1?1?1?1
```

I've got a Paperspace VM with an NVidia P6000 card in it, and it estimates this operation will take 60 days.  Does this estimation seem reasonable or did I miss a step somewhere that should make this operation happen a bit quicker?  

:-)

Thanks,
Brian

**Comment by evilmog** [comment]
for a single card that sounds about right, its about 40 GTX 980's for 3 days. You will need to use something like hashtopolis or a manual skip and limit calculator to distribute the load.
